### ISSUE TITLE
package install can't locate the plugin

### ISSUE THREAD

**Issue by stonefury** [sous-chefs/SublimeChef#18]
Trying to install the plugin from the package manager but it can't find "sublimechef". Do I need to install it manually?

**Comment by rkul** [comment]
Pls check your package control settings
https://packagecontrol.io/docs/settings
Chef package exist and could be installed: https://packagecontrol.io/packages/Chef
Might be you already have Chef plugin installed, pls look at Package Control: List Packages

**Comment by tas50** [comment]
Looks like the response is the solution. Closing this one out
