### ISSUE TITLE
 Add sytax checking to Circleci

### ISSUE THREAD

**Issue by Xorima** [sous-chefs/sublimechef#31]
Hopefully we could repurpose https://github.com/SublimeText/PackageDev/blob/master/.travis.yml

**Comment by onlyhavecans** [comment]
1. The official syntax checks are now in [GitHub Actions](https://github.com/SublimeText/PackageDev/tree/master/.github/workflows)
2. At this time this package does not have any syntax files; only has snippets, and there is no syntax checker for snippets. We can pull an XML linter in but I am 🤷🏻‍♀️ on that personally.

We _can_ add the official syntax.yml job, but it will be running against no files. I will defer to you @Xorima but I am not seeing the value.

**Comment by Xorima** [comment]
If they want it do it, then if we add any in future they will auto get handled

**Comment by onlyhavecans** [comment]
I addressed this and several other things in #51

**Comment by Xorima** [comment]
@onlyhavecans Thanks, I've approved it so you should be able to merge? (Go ahead when you are ready) any issues ping me on slack
