### ISSUE TITLE
Missing on Package Control

### ISSUE THREAD

**Issue by kmf** [sous-chefs/sublimechef#45]
![2021-07-13 at 10 20 39](https://user-images.githubusercontent.com/78700/125417480-338e5920-9213-4410-883c-98c91f5e33e9.png)

When going to [Package Control](https://packagecontrol.io/packages/Chef) it says the package is missing

**Comment by ddarbyson** [comment]
Yes, please fix.

**Comment by onlyhavecans** [comment]
I just loaded sublime text on a new machine and now it's gone!
I submitted a PR to Package Control's repo since it looks like they renamed the master branch to main and forgot to update PC

https://github.com/wbond/package_control_channel/pull/8674

**Comment by onlyhavecans** [comment]
My PR was rejected. A member of the sous-chef org will need to submit the change, as well as move the repository to tag-based releases.

See https://github.com/wbond/package_control_channel/pull/8674#issuecomment-1374455401

**Comment by onlyhavecans** [comment]
Now that I am a maintainer I have added tags and gitattributes as needed and reopened the request to fix the entry in package control

**Comment by onlyhavecans** [comment]
The PR is approved! 🎊 

It seems because the package was missing for so long there is a manual review process in addition. But we are steps closer to having this fixed!

**Comment by ddarbyson** [comment]
Thx guys!

**Comment by onlyhavecans** [comment]
Chef is fixed and back!!! 🎊
